### ISSUE TITLE
Lyo designer/generator not working under Eclipse Photon (or Sirius 6.1)

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.designer#75]
An error occurs upon generation, in the following setup:
- Eclipse Photon
- Sirius 6.1.2.201902150923
- Acceleo 3.7.2

log file:
!ENTRY org.eclipse.ui 4 0 2019-04-15 11:33:14.273 !MESSAGE Unhandled 
event loop exception !STACK 0
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException:
org.eclipse.emf.ecore.xmi.UnresolvedReferenceException: Unresolved reference '/0/generateForServiceProviderCatalog/anAdaptorInterface'.
(jar:file:/C:/Users/patrick/eclipse/java-photon/eclipse/plugins/org.ec
lipse.lyo.oslc4j.codegenerator_2.4.0.jar!/org/eclipse/lyo/oslc4j/codeg
enerator/main/generate.emtl,
83, 155)
    at
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadEx
ception(ResourceSetImpl.java:319)
    at
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(R
esourceSetImpl.java:278)
    at
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(Resour
ceSetImpl.java:406)
    at 
org.eclipse.acceleo.common.utils.ModelUtils.load(ModelUtils.java:391)
    at 
org.eclipse.acceleo.common.utils.ModelUtils.load(ModelUtils.java:356)
    at
org.eclipse.acceleo.engine.service.AbstractAcceleoGenerator.initialize
(AbstractAcceleoGenerator.java:485)
    at
org.eclipse.lyo.oslc4j.codegenerator.main.Generate.<init>(Generate.jav
a:90)
    at
org.eclipse.lyo.tools.codegenerator.ui.common.GenerateAll.<init>(Gener
ateAll.java:70)
    at
org.eclipse.lyo.tools.codegenerator.ui.popupMenus.AcceleoGenerateCodeg
eneratorAction.run(AcceleoGenerateCodegeneratorAction.java:107)
    at
org.eclipse.ui.actions.ActionDelegate.runWithEvent(ActionDelegate.java
:75)
    at
org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:23
7)
    at
org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(
ActionContributionItem.java:565)
    at
org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContrib
utionItem.java:397)
    at 
org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
    at 
org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
    at 
org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
    at
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(Par
tRenderingEngine.java:1170)
    at
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.jav
a:336)
    at
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartR
enderingEngine.java:1059)
    at
org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Work
bench.java:153)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
    at
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.jav
a:336)
    at
org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java
:597)
    at 
org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at
org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplic
ation.java:152)
    at
org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle
.java:196)
    at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplic
ation(EclipseAppLauncher.java:134)
    at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(Ecl
ipseAppLauncher.java:104)
    at
org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.jav
a:388)
    at
org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.jav
a:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at 
org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
Caused by: org.eclipse.emf.ecore.xmi.UnresolvedReferenceException:
Unresolved reference
'/0/generateForServiceProviderCatalog/anAdaptorInterface'.
(jar:file:/C:/Users/patrick/eclipse/java-photon/eclipse/plugins/org.ec
lipse.lyo.oslc4j.codegenerator_2.4.0.jar!/org/eclipse/lyo/oslc4j/codeg
enerator/main/generate.emtl,
83, 155)
    at
org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleForwardReferences(XMLH
andler.java:1197)
    at
org.eclipse.emf.ecore.xmi.impl.XMLHandler.endDocument(XMLHandler.java:
1282)
    at
com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocume
nt(Unknown
Source)
    at
com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl
.scanDocument(Unknown
Source)
    at
com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Un
known
Source)
    at
com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Un
known
Source)
    at
com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown 
Source)
    at
com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unk
nown
Source)
    at
com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.pa
rse(Unknown
Source)
    at
com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown 
Source)
    at 
org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
    at
org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.
java:261)
    at
org.eclipse.acceleo.model.mtl.resource.EMtlResourceImpl.doLoad(EMtlRes
ourceImpl.java:93)
    at
org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.jav
a:1563)
    at
org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.jav
a:1342)
    at
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(Resourc
eSetImpl.java:259)
    at
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(R
esourceSetImpl.java:274)
    ... 37 more

**Comment by jadelkhoury** [comment]
Problem seems to stem from some instabilities in Acceleo 3.7.
https://www.eclipse.org/forums/index.php?t=msg&th=1098273&goto=1806492&#msg_1806492

An installation of LyoDesigner on the following Eclipses, provides the following Acceleo & Sirius versions.

**eclipse 2019-03**
  * Sirius 6.1.2	
  * Acceleo 3.7.8	


**Eclipse Oxygen**
 * Acceleo 3.7.2	
 * Sirius 5.1.1

Maybe we should configure the build scripts to stick to Sirius 5 & Acceleo 3.7.2.

**Comment by jadelkhoury** [comment]
Restricting Acceleo/Sirius to specific old versions will likely cause problems when installing LyoDesigner, because it is not certain the updateSites for these old versions are configured by the end-user.

From the above Acceleo Forum post, hopefully Acceleo 3.7.8 will be fixed by an early EMF 2.18 (2019-06). That is less than 1 month from now. So, worth waiting with this fix until then.

We know Lyo Designer works with Eclipse 2018-09 and earlier, and that's what we can recommend to use, unless people want to tweek their Acceleo/Sirius/EMF versions.
